# Generated by Django 5.2.14 on 2026-06-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0004_alter_player_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('players', models.ManyToManyField(to='player.player')),
            ],
            options={
                'ordering': ['team'],
            },
        ),
    ]
