# Generated by Django 5.2.14 on 2026-06-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
