# Generated by Django 5.2.14 on 2026-06-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_alter_player_student'),
        ('team', '0002_alter_team_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, to='player.player', verbose_name='Players'),
        ),
    ]
