# Generated by Django 5.2.14 on 2026-06-06 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_player_student'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student', verbose_name='Student Information'),
        ),
    ]
