# Generated by Django 5.2.14 on 2026-06-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_name', models.CharField(blank=True, max_length=30, null=True)),
                ('suffix', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['last_name', 'first_name', 'middle_name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('first_name', ''), _negated=True), models.Q(('last_name', ''), _negated=True)), name='person_first_last_not_empty_str')],
            },
        ),
    ]
