# Generated by Django 5.2.14 on 2026-06-04 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='address.address'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('suffix', ''), _negated=True), ('suffix__isnull', False)), fields=('first_name', 'last_name', 'address', 'suffix'), name='person_name_address_suffix_unique_when_suffix_present'),
        ),
    ]
