# Generated by Django 5.2.14 on 2026-06-04 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('highschool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highschool',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='high_schools', to='address.address', verbose_name='High School Address'),
        ),
        migrations.AlterField(
            model_name='highschool',
            name='school_mascot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
