# Generated by Django 5.2.14 on 2026-06-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highschool', '0002_alter_highschool_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highschool',
            options={'ordering': ['school_name'], 'verbose_name': 'High School', 'verbose_name_plural': 'High Schools'},
        ),
    ]
