# Generated by Django 5.2.14 on 2026-06-07 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0004_alter_player_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, default=0, null=True)),
                ('pins', models.IntegerField(blank=True, default=0, null=True)),
                ('pin1', models.IntegerField(blank=True, default=0, null=True)),
                ('pin2', models.IntegerField(blank=True, default=0, null=True)),
                ('pin3', models.IntegerField(blank=True, default=0, null=True)),
                ('pin4', models.IntegerField(blank=True, default=0, null=True)),
                ('pin5', models.IntegerField(blank=True, default=0, null=True)),
                ('pin6', models.IntegerField(blank=True, default=0, null=True)),
                ('pin7', models.IntegerField(blank=True, default=0, null=True)),
                ('pin8', models.IntegerField(blank=True, default=0, null=True)),
                ('pin9', models.IntegerField(blank=True, default=0, null=True)),
                ('pin10', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField(blank=True, null=True)),
                ('score_before', models.IntegerField(blank=True, null=True)),
                ('bonus1', models.IntegerField(blank=True, null=True)),
                ('bonus2', models.IntegerField(blank=True, null=True)),
                ('score_after', models.IntegerField(blank=True, null=True)),
                ('is_started', models.BooleanField(default=False)),
                ('is_ball3', models.BooleanField(default=False)),
                ('is_bonus1', models.BooleanField(default=False)),
                ('is_bonus2', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ball1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frame_ball1', to='game.ball')),
                ('ball2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frame_ball2', to='game.ball')),
                ('ball3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frame_ball3', to='game.ball')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_score', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='game.finalscore')),
                ('frame1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_frame1', to='game.frame')),
                ('frame10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_frame10', to='game.frame')),
                ('frame2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_frame2', to='game.frame')),
                ('frame3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_frame3', to='game.frame')),
                ('frame4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_frame4', to='game.frame')),
                ('frame5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_frame5', to='game.frame')),
                ('frame6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_frame6', to='game.frame')),
                ('frame7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_frame7', to='game.frame')),
                ('frame8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_frame8', to='game.frame')),
                ('frame9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_frame9', to='game.frame')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='player.player')),
            ],
        ),
    ]
