# Generated by Django 5.2.14 on 2026-06-08 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_score_update_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='ball1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frame_ball1', to='game.ball'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='ball2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frame_ball2', to='game.ball'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='ball3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frame_ball3', to='game.ball'),
        ),
        migrations.AlterField(
            model_name='game',
            name='final_score',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.finalscore'),
        ),
        migrations.AlterField(
            model_name='game',
            name='frame1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_frame1', to='game.frame'),
        ),
        migrations.AlterField(
            model_name='game',
            name='frame10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_frame10', to='game.frame'),
        ),
        migrations.AlterField(
            model_name='game',
            name='frame2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_frame2', to='game.frame'),
        ),
        migrations.AlterField(
            model_name='game',
            name='frame3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_frame3', to='game.frame'),
        ),
        migrations.AlterField(
            model_name='game',
            name='frame4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_frame4', to='game.frame'),
        ),
        migrations.AlterField(
            model_name='game',
            name='frame5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_frame5', to='game.frame'),
        ),
        migrations.AlterField(
            model_name='game',
            name='frame6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_frame6', to='game.frame'),
        ),
        migrations.AlterField(
            model_name='game',
            name='frame7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_frame7', to='game.frame'),
        ),
        migrations.AlterField(
            model_name='game',
            name='frame8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_frame8', to='game.frame'),
        ),
        migrations.AlterField(
            model_name='game',
            name='frame9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_frame9', to='game.frame'),
        ),
    ]
