# Generated by Django 5.2.14 on 2026-06-05 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('highschool', '0003_alter_highschool_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('high_school', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='highschool.highschool', verbose_name='High School')),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'ordering': ['high_school__school_name'],
            },
        ),
    ]
