# Generated by Django 5.2.14 on 2026-06-04 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lanes', models.CharField(blank=True, max_length=55, null=True, verbose_name='Bowling Lanes Name')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address', verbose_name='Lanes Address')),
            ],
            options={
                'verbose_name': 'Lanes',
                'verbose_name_plural': 'Lanes',
                'ordering': ['lanes'],
            },
        ),
    ]
